#!/usr/bin/env zsh

# ex - archive extractor
# usage: ex <file>
function ex() {
  local source=$1

  if [ -z "$source" ]; then
    echo "Usage: ex <file>"
    echo "Example: ex foo.tar.gz"
    return 1
  fi

  if [ -f "$source" ]; then
    case "$source" in
    *.7z) 7z x "$source" ;;
    *.bz2) bunzip2 "$source" ;;
    *.tar.bz2) tar xjf "$source" ;;
    *.tar.gz) tar xzf "$source" ;;
    *.tar.xz) tar xJf "$source" ;;
    *.rar) unrar x "$source" ;;
    *.gz) gunzip "$source" ;;
    *.tar) tar xf "$source" ;;
    *.tbz2) tar xjf "$source" ;;
    *.tgz) tar xzf "$source" ;;
    *.xz) xz -d "$source" ;;
    *.zip) unzip "$source" ;;
    *.Z) uncompress "$source" ;;
    *) echo "'"$source"' cannot be extracted via ex()" ;;
    esac
  else
    echo "'"$source"' is not a valid file"
  fi
}

function compress() {
  local source="$1"
  local format="$2"
  local out="$3"
  local output=""

  if [ -z "$out" ]; then
    output="${source%.*}.$format"
  else
    output="$out.$format"
  fi

  if [ -z "$source" ] || [ -z "$format" ]; then
    echo "Usage: compress <source> <format> <name>"
    echo "Example: compress /path/to/directory tar.gz"
    return 1
  fi

  case "$format" in
  7z)
    7z a "$output" "$source"
    ;;
  bz2)
    tar -cjvf "$output" "$source"
    ;;
  gz)
    gzip "$source"
    mv "$source.gz" "$output"
    ;;
  rar)
    rar a "$output" "$source"
    ;;
  tbz2)
    tar -xjf "$source"
    mv "$source.tar" "$output"
    ;;
  tgz)
    tar -czvf "$output" "$source"
    ;;
  tar)
    tar -cvf "$output" "$source"
    ;;
  tar.bz2)
    tar -cjvf "$output" "$source"
    ;;
  tar.gz)
    tar -czvf "$output" "$source"
    ;;
  tar.xz)
    tar -cJvf "$output" "$source"
    ;;
  zip)
    zip -r "$output" "$source"
    ;;
  Z)
    compress "$source"
    mv "$source.Z" "$output"
    ;;
  *)
    echo "Unsupported format: $format"
    return 1
    ;;
  esac

  echo "Compression complete: $output"
}

function pack_man() {
  # Define aliases for Pacman-related commands
  function pacmanAlias() {
    alias pacman-update='sudo pacman-mirrors --geoip'
    alias fixpacman='sudo rm /var/lib/pacman/db.lck'
    # Get fastest mirrors
    alias mirror='sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist'
    alias mirrord='sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist'
    alias mirrors='sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist'
    alias mirrora='sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist'
  }

  # Define package management aliases based on available package manager
  if command -v apk &>/dev/null; then
    alias pkm='sudo apk add --no-cache '
  elif command -v apt-get &>/dev/null; then
    alias pkm='sudo apt install '
    alias rpkm='sudo apt remove'
    alias rpkmcleanup='sudo apt autoremove'
    alias packdate='sudo apt -y update && flatpak -y --noninteractive update'
  elif command -v dnf &>/dev/null; then
    alias pkm='sudo dnf install '
    alias rpkm='sudo dnf remove '
    alias rpkmcleanup='sudo dnf -y autoremove'
    alias packdate='sudo dnf -y upgrade --refresh'
  elif command -v zypper &>/dev/null; then
    alias pkm='sudo zypper install '
  elif command -v yay &>/dev/null || command -v paru &>/dev/null; then
    if command -v yay &>/dev/null && command -v paru &>/dev/null; then
      alias pkm='paru -S '
      alias rpkm='paru -Rdd'
      alias rpkmcleanup='paru -Rns $(paru -Qdtq)' # Cleanup orphaned packages
      alias pkmgrade='paru --noconfirm -Syu && sudo flatpak -y --noninteractive update'
    else
      alias pkm='yay -S '
      alias rpkm='yay -Rdd'
      alias rpkmcleanup='yay -Rns $(yay -Qdtq)' # Cleanup orphaned packages
      alias pkmgrade='yay --noconfirm -Syu && sudo flatpak -y --noninteractive update'
    fi
    pacmanAlias
  elif command -v nix-env &>/dev/null; then
    # Nix package manager
    alias pkm='nix-env -iA'
    alias rpkm='nix-env -e'
    alias rpkmcleanup='nix-collect-garbage -d'
    alias packdate='nix-channel --update'
  else
    echo 'This Distro is not supported!'
  fi
}

# Call the function to set up the aliases
pack_man

function build-cpp() {
  # Check if cmake is installed
  if ! command -v cmake &>/dev/null; then
    echo "cmake could not be found"
    return 1
  fi

  local build_target="build"
  local cmake_command="cmake"

  # If already inside the build directory, adjust build_target accordingly
  if [ "${PWD##*/}" = "build" ]; then
    build_target="."
  fi

  # Check if build directory exists, otherwise generate cmake build files
  if ! [[ -d "$build_target" ]]; then
    echo "Running $cmake_command -B $build_target..."
    $cmake_command -B $build_target
    if [ $? -ne 0 ]; then
      echo "Failed to run $cmake_command -B $build_target" >&2
      return 1
    fi
  fi

  echo "Building C++ project..."

  # Check if mold is installed and executable
  if [[ -x /usr/bin/mold || -x /bin/mold ]]; then
    mold --run cmake --build "$build_target" -- "$@"
  else
    cmake --build "$build_target" -j4 -- "$@"
  fi

  return 0
}

function reload() {
  case "$SHELL" in
  */bash)
    source ~/.bashrc
    ;;
  */zsh)
    source ~/.zshrc 2>/dev/null
    ;;
  *)
    echo "You are using another shell: $SHELL."
    ;;
  esac
}

function plugins() {
  case "$SHELL" in
  */zsh)
    vim ~/.config/zsh/plugins_config.zsh
    ;;
  *)
    echo "No plugin manager defined for: $SHELL."
    ;;
  esac
}

function run-bg() {
  nohup "$@" >/dev/null 2>&1 &
}
