export PATH="/home/flmr799e/.npm-global/lib/node_modules/.bin:$PATH"

export EDITOR=nvim
export VISUAL=nvim
### End of functions

# Load device specific configurations
[ -f "$HOME/.device_config" ] && source "$HOME/.device_config"

# Load functions
[ -f "$HOME/.functionsrc" ] && source "$HOME/.functionsrc"

# Load aliases and shortcuts if existent.
[ -f "$HOME/.aliasrc" ] && source "$HOME/.aliasrc"

# cargo env
[ -f ~/.cargo/env ] && source $HOME/.cargo/env

#starship
eval "$(starship init bash)"
