export PATH="/home/flmr799e/.npm-global/lib/node_modules/.bin:$PATH"

export EDITOR=nvim
export VISUAL=nvim
### End of functions

# Load device specific configurations
[ -f "$HOME/.device_config" ] && source "$HOME/.device_config"

# Load functions
[ -f "$HOME/.functionsrc" ] && source "$HOME/.functionsrc"

# Load aliases and shortcuts if existent.
if [ -f "$HOME/.aliasrc" ]; then
  source "$HOME/.aliasrc"
else
  alias ..='cd ..'
  alias cd..='cd ..'
  alias cp='cp -r'
  alias l='ls'
  alias lt='tree'
  alias reboot='sudo reboot'
  alias poweroff='sudo poweroff'
  alias shutdown='sudo shutdown now'
  alias suspend='systemctl suspend'
  alias sctl='sudo systemctl'
  alias usystemctl='systemctl --user'
  alias blkid='sudo blkid -o export'
  alias dlist='sudo blkid -o list'
  alias fontsReload='fc-cache -f -v'
  alias fontsList='fc-list'
  alias please='sudo $(fc -ln -1)'
  alias fuck='please'
  alias fck='please'
  alias open='xdg-open'
  alias cls='clear'
  alias vi='nvim'
  alias vim='nvim'
  alias svim='sudo -E nvim'
fi

# cargo env
[ -f ~/.cargo/env ] && source $HOME/.cargo/env

#starship
if command -v starship &>/dev/null; then
  eval "$(starship init zsh)"
fi
